spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:  ${DB_URL:jdbc:mysql://127.0.0.1:3306/sample?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true}
    driver-class-name: ${DB_DRIVER:com.mysql.jdbc.Driver}
    username:  ${DB_USER:spample}
    password:  ${DB_PASSWORD:spample-password}
    test-while-idle: true
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: true
  websocket:
    allowedOrigins: ${ALLOW_ORIGINS:localhost}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:localhost}
    non-secure-port: ${EUREKA_INSTANCE_PORT:80}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${eureka.instance.non-secure-port}:${random.value}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_SERVICE_URL:'http://localhost:8761/eureka/'}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.netflix.hystrix: WARN
    com.tundra: DEBUG
    com.soterianetworksgeek: DEBUG
